version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-taskmanager_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    container_name: taskmanager_app
    ports:
      - "5039:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME:-taskmanager_db};Username=${DB_USER:-postgres};Password=${DB_PASS:-postgres};"

volumes:
  postgres_data: