# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST https://localhost:7292/api/User/registrate
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "Email": "aboba",
    "Password" : "aboba"
}

###

POST https://localhost:7292/api/User/verify
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "Email": "aboba",
    "Password" : "aboba"
}

###

@Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkxY2FiMDdkLTgwM2QtNDlmYy00ZGYzLTA4ZGVlMTliYzI4OSIsImlzcyI6Ik15QXV0aFNlcnZlciIsImF1ZCI6Ik15QXV0aENsaWVudCJ9.VIe3JyskzIifeS7RQvK9zds6T9gLmv6oUYSDTzNiqlw
POST https://localhost:7292/api/Project/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Name": "aboba1"
}

###

POST https://localhost:7292/api/Project/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Name": "aboba2"
}

###

POST https://localhost:7292/api/Project/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Name": "aboba3"
}

###

POST https://localhost:7292/api/Project/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Name": "aboba4"
}

###

POST https://localhost:7292/api/Project/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Name": "aboba5"
}

###
GET https://localhost:7292/api/Project/GetAll
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

###

DELETE https://localhost:7292/api/Project/Delete
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}
{
    "Id": "b74ee616-e19a-4dc7-457f-08dee19bccf6"
}

###

# status can set by number or string (1 or "Complited")

PUT https://localhost:7292/api/Project/Update
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "Id": "58cd89a0-e8ea-48a3-457d-08dee19bccf6",
    "Name": "aboba3",
    "Status": "Complited"
}

###

GET https://localhost:7292/api/Project/Find
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "Status",
    "PropertyValue": "Complited",
    "FindFlags": 0
}

###

GET https://localhost:7292/api/Project/Filter
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "Id",
    "PropertyValue": "58cd89a0-e8ea-48a3-457d-08dee19bccf6",
    "FilterComparer": "GreateEqual"
}

###

GET https://localhost:7292/api/Project/GetPage
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "Number": 2,
    "Size": 3
}

###

GET https://localhost:7292/api/Project/Sort
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "Id",
    "SortMode": 0
}

###
@ProjectId1 = 0bc9349e-7e37-4d49-457b-08dee19bccf6
@ProjectId2 = a58cd453-4663-4554-457c-08dee19bccf6
POST https://localhost:7292/api/ProjectTask/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "ProjectId": "{{ProjectId1}}",
    "Title": "AbobaTask1",
    "Description": "jwnrieurne",
    "DueDate": "2026-07-18"
}

###

POST https://localhost:7292/api/ProjectTask/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "ProjectId": "{{ProjectId1}}",
    "Title": "AbobaTask2",
    "Description": "jwnriwmrfweurne",
    "DueDate": "2026-07-19"
}

###

POST https://localhost:7292/api/ProjectTask/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "ProjectId": "{{ProjectId2}}",
    "Title": "AbobaTask3",
    "Description": "jwnrwpmaposfvvvvvvieurne",
    "DueDate": "2026-07-20"
}

###

POST https://localhost:7292/api/ProjectTask/Create
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "ProjectId": "{{ProjectId2}}",
    "Title": "AbobaTask4",
    "Description": "jwnrieurnepslo[rkpekpa",
    "DueDate": "2026-07-21"
}

###
GET https://localhost:7292/api/ProjectTask/GetAll
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

###
@TaskId=0fa9c0e8-0cf3-4578-2a9a-08dee2939e8d
POST https://localhost:7292/api/ProjectTask/ChangeStatus
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "Id": "{{TaskId}}",
    "Status": "Done"
}

###

GET https://localhost:7292/api/ProjectTask/Find
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "Description",
    "PropertyValue": "Jwnriwmrfweurne",
    "FindFlags": 2
}

###

GET https://localhost:7292/api/ProjectTask/Filter
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "Id",
    "PropertyValue": "0fa9c0e8-0cf3-4578-2a9a-08dee2939e8d",
    "FilterComparer": "LessEqual"
}

###

GET https://localhost:7292/api/ProjectTask/Sort
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "PropertyName": "DueDate",
    "SortMode": 1
}

###

POST https://localhost:7292/api/ProjectTask/Delete
Content-Type: application/json
Accept-Language: en-US,en;q=0.5
Authorization: Bearer {{Token}}

{
    "Id": "{{TaskId}}"
}